dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - release-0.9
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "9"
  - "8"
  - "7"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get install ethereum
  - geth version
install:
  - npm install
before_script:
  - rm -rf test/st-poa-*
script:
  - cd test
  - source set_env_vars.sh
  - sh init_keys.sh
  - cat set_env_vars.sh
  - nohup sh run_value_chain.sh </dev/null >/dev/null 2>&1 &
  - node geth_checker.js value
  - nohup sh run_utility_chain.sh </dev/null >/dev/null 2>&1 &
  - node geth_checker.js utility
  - source set_env_vars.sh
  - sh setup_platform.sh travis
  - source set_env_vars.sh
  - cd ..
  - nohup node executables/inter_comm/stake_and_mint.js  </dev/null >/dev/null 2>&1 &
after_script:
  - kill $(ps aux | grep 'geth' | awk '{print $2}')