dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - release-0.9
  -- module
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "9"
  - "8"
  - "7"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get install ethereum
  - geth version
install:
  - npm install
before_script:
script:
  - node tools/setup/index.js test
after_script:
  - kill $(ps aux | grep 'geth' | awk '{print $2}')